title: ramses.eth
author: ramses.eth
email: ramseshk@pm.me
description: developer
url: "https://ramseshk.github.io/" 

# Build settings
remote_theme: huangyz0918/moving
plugins:
  - jekyll-feed

moving:
  about_you: developer
  avatar_url: https://i.loli.net/2019/09/07/wiBh3uMWRUaLX5K.png 
  date_format: "%b %d"
  back_to: "ramses.eth"
  social_links:
    rss: RSS
    github:  ramseshk
    facebook: ramseshk
    linkedin: ramseshk

